#+TITLE:DICTy - Dictyostelium Images Clustering and Tracking for pYthon.
#+Author:Guilhem Doulcier
#+Date:<2013-07-11 Thu 16:07>

DICTy (Dictyostelium Images Clustering and Tracking for pYthon) is a tool to automatically analyse Dictyostelium discoideum aggregations images. 

* Features

- Voronoi partition.
- Particle clustering using OPTICS algorithm [fn:Ankerst].
- Crowding and group size estimations.
- HTML export.

[fn:Ankerst] Mihael Ankerst, Markus M. Breunig, Hans-Peter Kriegel, Jörg Sander (1999). *OPTICS: Ordering Points To Identify the Clustering Structure*. /ACM SIGMOD international conference on Management of data/. ACM Press. pp. 49–60.

* Usage

Modify the run.py file examples to suit your needs.

* Requirements 
- Python 2.7
- Numpy and Scipy
- Matplotlib

* License
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
